name: retro_dash
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  simple_icons: ^14.6.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.8.0
  image_picker: ^0.8.6
  shared_preferences: ^2.3.2
  path_provider: ^2.1.1
  path: ^1.8.3
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
  assets:
    - assets/images/
    - assets/audio/blast.mp3
    - assets/audio/explosion.mp3
    - assets/audio/space_theme.mp3

  uses-material-design: true

